
insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0123', '西三环站', 'XISANHUAN', '2', null, null, '10.15.122.11', '012393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0111', '郑州大学站', 'ZHENGZHOU UNIVERSITY', '2', null, null, null, '011193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0100', 'ZhengZhouLC', 'ZhengZhouDiTie', '1', null, null, '1.1.1.1', '03007100');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('03', '0399', 'DSS', 'DSS', '3', null, null, '1.1.1.2', '03990601');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0113', '梧桐街站', 'WUTONGJIE', '2', null, null, null, '011393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0115', '兰寨站', 'LANZHAI', '2', null, null, null, '011593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0117', '铁炉站', 'TIELU', '2', null, null, null, '011793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0119', '市民中心站', 'CIVIC CENTER', '2', null, null, null, '011993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0161', '龙子湖站', 'LONGZIHU', '2', null, null, null, '016193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0163', '文苑北路站', 'WENYUANBEILU', '2', null, null, null, '016393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0165', '河南大学新区站', 'NEW CAMPUS OF HENAN UNIVERCITY', '2', null, null, null, '016593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0109', '郑大科技园站', 'ZHENGZHOU UNIVERSITY SCI-TECH PARK', '2', null, null, null, '010993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0107', '河南工业大学站', 'HENAN UNIVERSITY OF TECHNOLOGY', '2', null, null, '10.15.122.11', '010793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0121', '西流湖站', 'XILIUHU', '2', null, null, null, '012193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0125', '秦岭路站', 'QINLINGLU', '2', null, null, null, '012593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0127', '桐柏路站', 'TONGBAILU', '2', null, null, null, '012793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0129', '碧沙岗站', 'BISHAGANG', '2', null, null, null, '012993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0131', '绿城广场站', 'LUCHENGGUANGCHANG', '2', null, null, null, '013193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0133', '医学院站', 'YIXUANYUAN', '2', null, null, null, '013393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0135', '郑州火车站', 'ZHENGZHOU RAILWAY STATION', '2', null, null, null, '013593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0137', '二七广场站', 'ERQIGUANGCHANG', '2', null, null, null, '013793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0139', '人民路站', 'RENMINLU', '2', null, null, null, '013993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0141', '紫荆山站', 'ZIJINGSHAN', '2', null, null, null, '014193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0143', '燕庄站', 'YANZHUANG', '2', null, null, null, '014393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0145', '民航路站', 'MINHANGLU', '2', null, null, null, '014593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0147', '会展中心站', 'CONVENTION  EXHIBITION CENTER', '2', null, null, null, '014793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0149', '黄河南路站', 'HUANGHENANLU', '2', null, null, null, '014993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0151', '农业南路站', 'NONGYENANLU', '2', null, null, null, '015193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0153', '东风南路站', 'DONGFENGNANLU', '2', null, null, null, '015393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0155', '郑州东站', 'ZHENGZHOU EAST RAILWAY STATION', '2', null, null, null, '015593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0157', '博学路站', 'BOXUELU', '2', null, null, null, '015793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('01', '0159', '市体育中心站', 'ZHENGZHOU SPORTS CENTER', '2', null, null, null, '015993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0221', '刘庄站', 'LIUZHUANG', '2', null, null, null, '022193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0223', '柳林站', 'LIULIN', '2', null, null, null, '022393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0225', '沙门站', 'SHAMEN', '2', null, null, null, '022593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0227', '北三环站', 'BEISANHUAN', '2', null, null, null, '022793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0229', '东风路站', 'DONGFENGLU', '2', null, null, null, '022993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0231', '关虎屯站', 'GUANHUTUN', '2', null, null, null, '023193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0233', '黄河路站', 'HUANGHELU', '2', null, null, null, '023393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0235', '紫荆山站', 'ZIJINGSHAN', '2', null, null, null, '023593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0237', '东大街站', 'DONGDAJIE', '2', null, null, null, '023793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0239', '陇海东路站', 'LONGHAIDONGLU', '2', null, null, null, '023993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0241', '二里岗站', 'ERLIGANG', '2', null, null, null, '024193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0243', '南五里堡站', 'NANWULIBAO', '2', null, null, null, '024393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0245', '花寨站', 'HUAZHAI', '2', null, null, null, '024593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0247', '南三环站', 'NANSANHUAN', '2', null, null, null, '024793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0249', '站马屯站', 'ZHANMATUN', '2', null, null, null, '024993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('02', '0251', '南四环站', 'NANSIHUAN', '2', null, null, null, '025193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6021', '十八里河站', 'SHIBALIHE', '2', null, null, null, '602193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6023', '沙窝李站', 'SHAWOLI', '2', null, null, null, '602393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6025', '双湖大道站', 'SHUANGHUDADAO', '2', null, null, null, '602593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6027', '小乔站', 'XIAOQIAO', '2', null, null, null, '602793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6029', '华南城西站', 'HUA"NANCHENG WEST', '2', null, null, null, '602993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6031', '华南城站', 'HUA"NANCHENG', '2', null, null, null, '603193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6033', '华南城东站', 'HUA"NANCHENGDONG', '2', null, null, null, '603393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6035', '孟庄站', 'MENGZHUANG', '2', null, null, null, '603593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6037', '港区北站', 'GANGQU NORTH', '2', null, null, null, '603793001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6039', '康平湖站', 'KANGPINGHU', '2', null, null, null, '603993001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6041', '兰河公园站', 'LANHEGONGYUAN', '2', null, null, null, '604193001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6043', '恩平湖站', 'ENPINGHU', '2', null, null, null, '604393001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6045', '综合保税区站', 'ZONGHEBAOSHUIQU', '2', null, null, null, '604593001');

insert into basi_station_info (LINE_ID, STATION_ID, STATION_CN_NAME, STATION_EN_NAME, LOCATION_TYPE, LOCATION_ID, LOCATION_NUMBER, STATION_IP, DEVICE_ID)
values ('60', '6047', '新郑机场站', 'XINZHENG INTERNATIONAL AIRPORT', '2', null, null, null, '604793001');

